# Statistical Experimentation

In [12]:
data = np.array([13, 28, 56, 31, 63])

sample = np.random.choice(data, 5, replace=False)

print(sample)

[31 63 56 13 28]


In [2]:
import numpy as np

groups= ['A', 'B']

assignment= np.random.choice(groups, 50)


print(assignment)

['A' 'B' 'B' 'A' 'B' 'B' 'B' 'B' 'A' 'B' 'B' 'A' 'B' 'B' 'B' 'A' 'B' 'B'
 'B' 'B' 'B' 'A' 'A' 'A' 'A' 'B' 'B' 'B' 'B' 'B' 'A' 'B' 'A' 'A' 'B' 'A'
 'B' 'A' 'A' 'A' 'A' 'B' 'A' 'B' 'A' 'A' 'A' 'A' 'B' 'A']


In [3]:
import numpy as np

np.random.seed(42)

sample = np.random.randint(0, 11, 5)
print(sample)

[ 6  3 10  7  4]


In [5]:
data = np.array([13, 28, 56, 31, 63])

sample = np.random.choice(data, 5)

print(sample)

[28 56 56 56 63]


In [7]:
import numpy as np

samples = np.random.poisson(10, 100)

print(samples)

[11 14  7  8  9 11  8 10  7 11 11  8 12  6  7  8 10  5  3  9 13  8  6 13
 12 13  9 14  8  8 12 15 13 13 10  8 15  9  7  8 13 15  8  7  9  6 16 10
 18 10  8 11  3 15  6  7  9 11  8 12 10 11 12 16  8  7 13 10 15  8 11 11
  5 10 11 12  8 11 11  5  8 13 11  7  8 11 15  8 14  6 16 11  6 14 12  9
 10 13 15  9]


In [12]:
import numpy as np

sample = np.random.choice(["Win", "Lose"], 10, p=(0.03, 0.97))

print(sample)

['Lose' 'Lose' 'Lose' 'Lose' 'Lose' 'Lose' 'Lose' 'Lose' 'Win' 'Lose']


In [17]:
import numpy as np
from scipy.stats import binom

sample = binom.rvs(10, 0.5, loc=0, size=100)

print(sample)

[6 5 4 4 6 6 6 6 3 5 3 5 5 7 4 3 3 6 5 3 3 6 3 6 6 3 3 8 4 4 6 8 8 6 4 3 6
 5 5 7 3 5 2 5 3 3 3 6 6 5 8 4 4 7 4 8 2 8 2 7 5 9 3 5 8 5 6 6 5 6 5 7 2 4
 8 7 5 5 4 4 5 4 5 3 8 8 6 5 4 6 6 3 7 6 8 6 5 5 7 7]


In [18]:
import numpy as np

seed = 121120
np.random.seed(seed)


print(np.random.poisson(5, 50))

[ 2  7  4  7  3  8  5  3 10  6  6  7  5  6  9  2  6  2  5  5  7  6  5  1
  8  3  6  5  2  4  3  3  3  5  9  4  8  4  4  5  3 10  4  7  3  3  7  1
  3  5]


In [20]:
import numpy as np
from scipy.stats import norm

sample = norm.rvs(size=20000)

print(sample)

[-1.03999015  1.50246117 -1.5778003  ...  1.26906225  1.84894874
 -0.07375503]


In [22]:
from scipy.stats import norm

prob = norm.cdf(60, 71, 15)

print(prob)


0.23167757463479827
