In [14]:
import tensorflow as tf

In [15]:
t1 = tf.constant([1,2])
t1

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [16]:
changeable_tensor = tf.Variable([2,3,4], dtype='float16')
changeable_tensor

<tf.Variable 'Variable:0' shape=(3,) dtype=float16, numpy=array([2., 3., 4.], dtype=float16)>

In [18]:
tf.expand_dims(changeable_tensor, axis=1)

<tf.Tensor: shape=(3, 1), dtype=float16, numpy=
array([[2.],
       [3.],
       [4.]], dtype=float16)>